"""add semantic_hash index

Revision ID: c04375161555
Revises: 7dcc67ab31b3
Create Date: 2026-04-11 21:47:53.593304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c04375161555'
down_revision: Union[str, None] = '7dcc67ab31b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('semantic_hash', sa.String(), nullable=True))
    op.alter_column('extractions', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('extractions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_extractions_created_at'), 'extractions', ['created_at'], unique=False)
    op.create_index(op.f('ix_extractions_semantic_hash'), 'extractions', ['semantic_hash'], unique=False)
    op.create_index(op.f('ix_extractions_status'), 'extractions', ['status'], unique=False)
    op.alter_column('pharmacist_actions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('pharmacist_actions_extraction_id_fkey', 'pharmacist_actions', type_='foreignkey')
    op.create_foreign_key(None, 'pharmacist_actions', 'extractions', ['extraction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pharmacist_actions', type_='foreignkey')
    op.create_foreign_key('pharmacist_actions_extraction_id_fkey', 'pharmacist_actions', 'extractions', ['extraction_id'], ['id'])
    op.alter_column('pharmacist_actions', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_extractions_status'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_semantic_hash'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_created_at'), table_name='extractions')
    op.alter_column('extractions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('extractions', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('extractions', 'semantic_hash')
    # ### end Alembic commands ###
